name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          pip install uv

      - name: Build and publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
        run: |
          uv build
          uv publish 2>&1 | tee publish_output.txt || {
            if grep -q "400 File already exists" publish_output.txt; then
              echo "Package version already exists on PyPI, skipping"
              exit 0
            else
              cat publish_output.txt
              exit 1
            fi
          }
